# Generated by Django 5.0.8 on 2024-08-10 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
