# Generated by Django 5.0.8 on 2024-08-13 15:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_alter_media_options_alter_media_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
