# Generated by Django 5.0.8 on 2024-08-13 17:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_media_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='image',
        ),
        migrations.AlterField(
            model_name='media',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
