# Generated by Django 5.0.8 on 2024-08-21 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_remove_media_image_alter_media_featured_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Media',
            new_name='Gallery',
        ),
    ]
